[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "poliwag"
version = "0.1.0"
description = "Prediction Of Lipopeptides Within Actinobacterial Genomes"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Barbara Terlouw", email = "barbara.terlouw@wur.nl" }]

dependencies = [
    "paras",
    "biopython"
]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
your-cli = "poliwag.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]